### ISSUE TITLE
Store shows 404 page

### ISSUE THREAD

**Issue by westhecool** [Dashactyl-Development/Dashactyl-0.4#1]
When you try to buy something on the store it takes you to a 404 page what is going wrong?

**Comment by r-kjha** [comment]
This happens when you have disabled the shop. Go to settings and enable coins and shop.

**Comment by westhecool** [comment]
> This happens when you have disabled the shop. Go to settings and enable coins and shop.

but it is: ```"enabled": true```

**Comment by westhecool** [comment]
Never mind the issue has seemed to have fixed itself
